server:
  port: 7000

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASS:123456}@${MONGO_HOST:103.216.117.244}:${MONGO_PORT:27017}/job-profile-service?authSource=admin
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:103.216.117.244}:${KAFKA_PORT:9095}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: job-profile-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9999/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

feign:
  multipart:
    enabled: true

oauth2:
  identity:
    client-id: ${CLIENT_ID:1}
    client-secret: ${CLIENT_SECRET:2}
    redirect-uri: ${REDIRECT_URI:3}

resilience4j:
  circuitbreaker:
    instances:
      companyService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true

file:
  service:
    url: http://localhost:8083
