server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Set-Cookie
            allowCredentials: true

      routes:
        - id: identity-route
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
          filters:
            - AuthenticationFilter

        - id: file-route
          uri: lb://file-service
          predicates:
            - Path=/files/**
          filters:
            - AuthenticationFilter

        - id: notification-route
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - AuthenticationFilter

        - id: job-route
          uri: lb://job-service
          predicates:
            - Path=/job/**
          filters:
            - AuthenticationFilter

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9999/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

gateway:
  url: ${GATEWAY_URL:http://localhost:8000}