server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9999/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always